<?php

use App\Http\Controllers\Api\Admin\DashboardController;
use App\Http\Controllers\Api\Admin\ArticleController;
use App\Http\Controllers\Api\Admin\CommentController;
use App\Http\Controllers\Api\Admin\ContentController;
use App\Http\Controllers\Api\Admin\DiscountController;
use App\Http\Controllers\Api\Admin\OrderController;
use App\Http\Controllers\Api\Admin\MediaController;
use App\Http\Controllers\Api\Admin\ProductController;
use App\Http\Controllers\Api\Admin\ShippingController;
use App\Http\Controllers\Api\Admin\SettingController;
use App\Http\Controllers\Api\Admin\TaxonomyController;
use App\Http\Controllers\Api\Admin\UserController;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\CatalogController;
use App\Http\Controllers\Api\StorefrontController;
use App\Http\Controllers\Api\AddressController;
use App\Http\Controllers\Api\CartController;
use App\Http\Controllers\Api\CheckoutController;
use App\Http\Controllers\Api\ContentController as PublicContentController;
use App\Http\Controllers\Api\EngagementController;
use App\Http\Controllers\Api\ProfileController;
use App\Http\Controllers\Api\ProductDiscoveryController;
use App\Http\Controllers\Api\Admin\QuestionController;
use App\Http\Controllers\Api\Admin\DiscoveryAnalyticsController;
use App\Http\Controllers\Api\Admin\InventoryController;
use App\Http\Controllers\Api\Admin\SalesReportController;
use App\Http\Controllers\Api\SeoController;
use App\Http\Controllers\Api\ReturnRequestController;
use App\Http\Controllers\Api\Admin\ReturnRequestController as AdminReturnRequestController;
use App\Http\Controllers\Api\SupportController;
use App\Http\Controllers\Api\SupportTicketController;
use App\Http\Controllers\Api\Admin\SupportTicketController as AdminSupportTicketController;
use App\Http\Controllers\Api\CampaignController;
use App\Http\Controllers\Api\Admin\CampaignController as AdminCampaignController;
use App\Http\Controllers\Api\NotificationController;
use App\Http\Controllers\Api\LocationController;
use App\Http\Controllers\Api\Admin\LocationController as AdminLocationController;
use App\Http\Controllers\Api\Admin\AttributeController;
use App\Http\Controllers\Api\Admin\NotificationController as AdminNotificationController;
use App\Http\Controllers\Api\Admin\AuditLogController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->group(function () {
    Route::get('store/bootstrap', [StorefrontController::class, 'bootstrap']);
    Route::get('store/home', [StorefrontController::class, 'home']);
    Route::get('campaigns/active', [CampaignController::class, 'active']);
    Route::get('seo/sitemap', [SeoController::class, 'sitemap']);
    Route::get('support/faq', [SupportController::class, 'faq']);
    Route::get('locations/provinces', [LocationController::class, 'provinces']);
    Route::get('locations/cities', [LocationController::class, 'cities']);
    Route::get('support/pages/{page}', [SupportController::class, 'page']);
    Route::post('auth/otp/request', [AuthController::class, 'requestOtp'])->middleware('throttle:5,1');
    Route::post('auth/otp/verify', [AuthController::class, 'verify'])->middleware('throttle:10,1');
    Route::get('catalog/categories', [CatalogController::class, 'categories']);
    Route::get('catalog/products', [CatalogController::class, 'products']);
    Route::get('catalog/filters', [ProductDiscoveryController::class, 'filters']);
    Route::get('catalog/suggestions', [ProductDiscoveryController::class, 'suggestions'])->middleware('throttle:30,1');
    Route::get('catalog/compare', [PublicContentController::class, 'compare']);
    Route::get('catalog/products/{slug}', [CatalogController::class, 'show']);
    Route::get('catalog/products/{product}/comments', [PublicContentController::class, 'productComments']);
    Route::get('catalog/products/{product}/related', [ProductDiscoveryController::class, 'related']);
    Route::get('catalog/products/{product}/price-history', [ProductDiscoveryController::class, 'priceHistory']);
    Route::get('catalog/products/{product}/questions', [ProductDiscoveryController::class, 'questions']);
    Route::get('articles', [PublicContentController::class, 'articles']);
    Route::get('articles/{slug}', [PublicContentController::class, 'article']);
    Route::get('payment/callback/{payment}', [CheckoutController::class, 'callback'])->name('payment.callback');
    Route::middleware('auth.api')->group(function () {
        Route::get('auth/me', [AuthController::class, 'me']);
        Route::put('auth/profile', [AuthController::class, 'updateProfile']);
        Route::delete('auth/logout', [AuthController::class, 'logout']);
        Route::get('cart', [CartController::class, 'index']);
        Route::post('cart', [CartController::class, 'store']);
        Route::patch('cart/{cartItem}', [CartController::class, 'update']);
        Route::delete('cart/{cartItem}', [CartController::class, 'destroy']);
        Route::apiResource('addresses', AddressController::class)->except(['show']);
        Route::get('checkout/options', [CheckoutController::class, 'options']);
        Route::post('checkout/discount', [CheckoutController::class, 'discount']);
        Route::post('checkout', [CheckoutController::class, 'store']);
        Route::get('profile/dashboard', [ProfileController::class, 'dashboard']);
        Route::get('profile/orders', [ProfileController::class, 'orders']);
        Route::get('profile/orders/{order}', [ProfileController::class, 'order']);
        Route::get('profile/orders/{order}/invoice', [ProfileController::class, 'invoice']);
        Route::get('profile/returns', [ReturnRequestController::class, 'index']);
        Route::post('profile/orders/{order}/returns', [ReturnRequestController::class, 'store']);
        Route::get('profile/tickets', [SupportTicketController::class, 'index']);
        Route::post('profile/tickets', [SupportTicketController::class, 'store']);
        Route::get('profile/tickets/{ticket}', [SupportTicketController::class, 'show']);
        Route::post('profile/tickets/{ticket}/replies', [SupportTicketController::class, 'reply']);
        Route::delete('profile/tickets/{ticket}', [SupportTicketController::class, 'close']);
        Route::get('favorites', [EngagementController::class, 'favorites']);
        Route::post('favorites/{product}', [EngagementController::class, 'toggleFavorite']);
        Route::get('saved-articles', [EngagementController::class, 'savedArticles']);
        Route::post('saved-articles/{article}', [EngagementController::class, 'toggleArticle']);
        Route::post('comments/{comment}/helpful', [EngagementController::class, 'vote']);
        Route::post('comments/{type}/{id}', [EngagementController::class, 'comment']);
        Route::post('catalog/products/{product}/questions', [ProductDiscoveryController::class, 'ask']);
        Route::post('catalog/products/{product}/alerts', [ProductDiscoveryController::class, 'alert']);
        Route::get('notifications', [NotificationController::class, 'index']);
        Route::patch('notifications/{notification}/read', [NotificationController::class, 'read']);
        Route::patch('notifications/read-all', [NotificationController::class, 'readAll']);
    });
    Route::prefix('admin')->middleware(['auth.api', 'ability:admin.access', 'audit.admin'])->group(function () {
        Route::get('dashboard', DashboardController::class);
        Route::get('audit-logs', [AuditLogController::class, 'index']);
        Route::get('locations', [AdminLocationController::class, 'index']);
        Route::get('attributes', [AttributeController::class, 'index']);
        Route::post('attributes', [AttributeController::class, 'store']);
        Route::put('attributes/{attribute}', [AttributeController::class, 'update']);
        Route::delete('attributes/{attribute}', [AttributeController::class, 'destroy']);
        Route::post('attributes/{attribute}/values', [AttributeController::class, 'storeValue']);
        Route::put('attribute-values/{value}', [AttributeController::class, 'updateValue']);
        Route::delete('attribute-values/{value}', [AttributeController::class, 'destroyValue']);
        Route::post('locations/provinces', [AdminLocationController::class, 'storeProvince']);
        Route::put('locations/provinces/{province}', [AdminLocationController::class, 'updateProvince']);
        Route::delete('locations/provinces/{province}', [AdminLocationController::class, 'deleteProvince']);
        Route::post('locations/cities', [AdminLocationController::class, 'storeCity']);
        Route::put('locations/cities/{city}', [AdminLocationController::class, 'updateCity']);
        Route::delete('locations/cities/{city}', [AdminLocationController::class, 'deleteCity']);
        Route::post('media', [MediaController::class, 'store']);
        Route::delete('media', [MediaController::class, 'destroy']);
        Route::apiResource('users', UserController::class)->only(['index', 'show', 'update', 'destroy']);
        Route::get('roles', [UserController::class, 'roles']);
        Route::post('roles', [UserController::class, 'storeRole']);
        Route::put('roles/{role}', [UserController::class, 'updateRole']);
        Route::delete('roles/{role}', [UserController::class, 'deleteRole']);
        Route::apiResource('products', ProductController::class);
        Route::apiResource('discounts', DiscountController::class);
        Route::apiResource('campaigns', AdminCampaignController::class)->except(['show']);
        Route::get('notifications', [AdminNotificationController::class, 'index']);
        Route::post('notifications', [AdminNotificationController::class, 'store']);
        Route::get('orders', [OrderController::class, 'index']);
        Route::get('orders/{order}', [OrderController::class, 'show']);
        Route::patch('orders/{order}/status', [OrderController::class, 'updateStatus']);
        Route::put('orders/{order}/shipment', [OrderController::class, 'shipment']);
        Route::post('orders/{order}/shipment/events', [OrderController::class, 'shipmentEvent']);
        Route::apiResource('articles', ArticleController::class);
        Route::get('comments', [CommentController::class, 'index']);
        Route::get('questions', [QuestionController::class, 'index']);
        Route::get('discovery-analytics', DiscoveryAnalyticsController::class);
        Route::get('inventory', [InventoryController::class, 'index']);
        Route::patch('inventory/{variant}', [InventoryController::class, 'adjust']);
        Route::get('inventory/{variant}/movements', [InventoryController::class, 'movements']);
        Route::get('reports/sales', [SalesReportController::class, 'index']);
        Route::get('reports/sales/export', [SalesReportController::class, 'export']);
        Route::get('returns', [AdminReturnRequestController::class, 'index']);
        Route::patch('returns/{returnRequest}', [AdminReturnRequestController::class, 'update']);
        Route::post('returns/{returnRequest}/refund', [AdminReturnRequestController::class, 'refund']);
        Route::get('support/tickets', [AdminSupportTicketController::class, 'index']);
        Route::get('support/tickets/{ticket}', [AdminSupportTicketController::class, 'show']);
        Route::post('support/tickets/{ticket}/replies', [AdminSupportTicketController::class, 'reply']);
        Route::patch('support/tickets/{ticket}', [AdminSupportTicketController::class, 'update']);
        Route::patch('questions/{question}', [QuestionController::class, 'answer']);
        Route::delete('questions/{question}', [QuestionController::class, 'destroy']);
        Route::patch('comments/{comment}', [CommentController::class, 'moderate']);
        Route::delete('comments/{comment}', [CommentController::class, 'destroy']);
        Route::post('comments/{comment}/replies', [CommentController::class, 'reply']);
        Route::get('content/{resource}', [ContentController::class, 'index']);
        Route::post('content/{resource}', [ContentController::class, 'store']);
        Route::put('content/{resource}/{id}', [ContentController::class, 'update']);
        Route::delete('content/{resource}/{id}', [ContentController::class, 'destroy']);
        Route::get('shipping/methods', [ShippingController::class, 'methods']);
        Route::post('shipping/methods', [ShippingController::class, 'storeMethod']);
        Route::put('shipping/methods/{method}', [ShippingController::class, 'updateMethod']);
        Route::delete('shipping/methods/{method}', [ShippingController::class, 'deleteMethod']);
        Route::get('shipping/slots', [ShippingController::class, 'slots']);
        Route::post('shipping/slots', [ShippingController::class, 'storeSlot']);
        Route::put('shipping/slots/{slot}', [ShippingController::class, 'updateSlot']);
        Route::delete('shipping/slots/{slot}', [ShippingController::class, 'deleteSlot']);
        Route::get('categories', [TaxonomyController::class, 'categories']);
        Route::post('categories', [TaxonomyController::class, 'storeCategory']);
        Route::put('categories/{category}', [TaxonomyController::class, 'updateCategory']);
        Route::delete('categories/{category}', [TaxonomyController::class, 'deleteCategory']);
        Route::get('brands', [TaxonomyController::class, 'brands']);
        Route::post('brands', [TaxonomyController::class, 'storeBrand']);
        Route::put('brands/{brand}', [TaxonomyController::class, 'updateBrand']);
        Route::delete('brands/{brand}', [TaxonomyController::class, 'deleteBrand']);
        Route::get('settings', [SettingController::class, 'index']);
        Route::put('settings', [SettingController::class, 'update']);
    });
});
