<?php
namespace App\Http\Controllers\Api\Admin;
use App\Http\Controllers\Controller;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;use Illuminate\Validation\Rule;
class LocationController extends Controller{
 public function index(){return DB::table('provinces')->orderBy('sort_order')->orderBy('name')->get()->map(function($p){$p->cities=DB::table('cities')->where('province_id',$p->id)->orderBy('sort_order')->orderBy('name')->get();return $p;});}
 public function storeProvince(Request $r){$d=$r->validate(['name'=>'required|string|max:100|unique:provinces,name','slug'=>'nullable|string|max:120|unique:provinces,slug','sort_order'=>'sometimes|integer|min:0','is_active'=>'sometimes|boolean']);$d['slug']=$d['slug']??Str::slug($d['name']).'-'.Str::lower(Str::random(4));$id=DB::table('provinces')->insertGetId($d+['created_at'=>now(),'updated_at'=>now()]);return response()->json(DB::table('provinces')->find($id),201);}
 public function updateProvince(Request $r,int $province){abort_unless(DB::table('provinces')->where('id',$province)->exists(),404);$d=$r->validate(['name'=>['required','string','max:100',Rule::unique('provinces')->ignore($province)],'slug'=>['nullable','string','max:120',Rule::unique('provinces')->ignore($province)],'sort_order'=>'sometimes|integer|min:0','is_active'=>'sometimes|boolean']);DB::table('provinces')->where('id',$province)->update($d+['updated_at'=>now()]);return DB::table('provinces')->find($province);}
 public function deleteProvince(int $province){abort_if(DB::table('addresses')->where('province_id',$province)->exists(),422,'این استان در آدرس کاربران استفاده شده است.');DB::table('provinces')->where('id',$province)->delete();return response()->noContent();}
 public function storeCity(Request $r){$d=$r->validate(['province_id'=>'required|exists:provinces,id','name'=>['required','string','max:100',Rule::unique('cities')->where(fn($q)=>$q->where('province_id',$r->province_id))],'slug'=>'nullable|string|max:120','sort_order'=>'sometimes|integer|min:0','is_active'=>'sometimes|boolean']);$d['slug']=$d['slug']??Str::slug($d['name']).'-'.Str::lower(Str::random(4));$id=DB::table('cities')->insertGetId($d+['created_at'=>now(),'updated_at'=>now()]);return response()->json(DB::table('cities')->find($id),201);}
 public function updateCity(Request $r,int $city){$row=DB::table('cities')->find($city);abort_unless($row,404);$d=$r->validate(['name'=>['required','string','max:100',Rule::unique('cities')->where(fn($q)=>$q->where('province_id',$row->province_id))->ignore($city)],'slug'=>'nullable|string|max:120','sort_order'=>'sometimes|integer|min:0','is_active'=>'sometimes|boolean']);DB::table('cities')->where('id',$city)->update($d+['updated_at'=>now()]);return DB::table('cities')->find($city);}
 public function deleteCity(int $city){abort_if(DB::table('addresses')->where('city_id',$city)->exists(),422,'این شهر در آدرس کاربران استفاده شده است.');DB::table('cities')->where('id',$city)->delete();return response()->noContent();}
}
