<script setup lang="ts">
const {api,token}=useShopApi(),{cart,load}=useCart()
const {data:boot}=await useAsyncData('store-bootstrap',()=>api<any>('/store/bootstrap'))
const {data:categories}=await useAsyncData('store-categories',()=>api<any[]>('/catalog/categories'))
const q=ref(''),suggestions=ref<any[]>([]),searching=ref(false),searchOpen=ref(false)
const title=computed(()=>boot.value?.settings?.site_title||'هنرمارکت')
let timer:ReturnType<typeof setTimeout>
watch(q,value=>{clearTimeout(timer);if(value.trim().length<2){suggestions.value=[];searchOpen.value=false;return}searching.value=true;timer=setTimeout(async()=>{try{suggestions.value=await api<any[]>('/catalog/suggestions',{query:{q:value}});searchOpen.value=true}finally{searching.value=false}},250)})
onMounted(()=>{if(token.value)load()})
function search(){if(q.value.trim()){searchOpen.value=false;navigateTo(`/products?search=${encodeURIComponent(q.value)}`)}}
function selectSuggestion(item:any){q.value=item.title;searchOpen.value=false;navigateTo(`/products/${item.slug}`)}
</script>
<template><div class="min-h-screen bg-stone-50 text-slate-800"><div class="bg-brand-900 px-4 py-2 text-center text-xs text-white">ارسال رایگان برای سفارش‌های منتخب • خرید مستقیم از هنرمند ایرانی</div><header class="sticky top-0 z-40 border-b bg-white/95 backdrop-blur"><div class="mx-auto flex max-w-7xl items-center gap-3 px-4 py-4"><NuxtLink to="/" class="flex shrink-0 items-center gap-2"><span class="grid size-10 place-items-center rounded-2xl bg-brand-700 text-xl font-black text-white">هـ</span><span class="hidden text-lg font-black text-brand-900 sm:block">{{title}}</span></NuxtLink><form class="relative flex-1" @submit.prevent="search"><input v-model="q" class="h-11 w-full rounded-xl bg-slate-100 px-4 text-sm outline-none focus:ring-4 focus:ring-brand-100" placeholder="جست‌وجوی محصول، دسته یا هنرمند…" @focus="searchOpen=!!suggestions.length"><button class="absolute left-2 top-2 px-3 py-1 text-slate-500">{{searching?'…':'⌕'}}</button><div v-if="searchOpen" class="absolute inset-x-0 top-12 z-50 overflow-hidden rounded-2xl border bg-white p-2 shadow-2xl"><button v-for="item in suggestions" :key="item.slug" type="button" class="flex w-full items-center justify-between rounded-xl px-4 py-3 text-right text-sm hover:bg-brand-50" @click="selectSuggestion(item)"><span class="font-bold">{{item.title}}</span><span class="text-slate-300">←</span></button><button type="submit" class="w-full border-t px-4 py-3 text-right text-xs font-bold text-brand-700">مشاهده همه نتایج برای «{{q}}»</button></div></form><NuxtLink :to="token?'/profile':'/login'" class="rounded-xl border px-4 py-2.5 text-sm font-bold">{{token?'حساب من':'ورود'}}</NuxtLink><NuxtLink to="/cart" class="relative grid size-11 place-items-center rounded-xl bg-brand-50 text-sm font-bold text-brand-700">سبد<span v-if="cart.count" class="absolute -left-1 -top-1 grid size-5 place-items-center rounded-full bg-rose-600 text-[10px] text-white">{{cart.count}}</span></NuxtLink></div><nav class="mx-auto flex max-w-7xl gap-6 overflow-x-auto px-4 pb-3 text-sm font-bold text-slate-600"><NuxtLink to="/products" class="shrink-0 text-brand-700">همه محصولات</NuxtLink><NuxtLink v-for="c in categories" :key="c.id" :to="`/products?category=${c.slug}`" class="shrink-0 hover:text-brand-700">{{c.title}}</NuxtLink><NuxtLink to="/blog" class="shrink-0">مجله</NuxtLink></nav></header><main><slot/></main><footer class="mt-20 border-t bg-white"><div class="mx-auto grid max-w-7xl gap-8 px-4 py-12 md:grid-cols-4"><div><p class="text-lg font-black text-brand-900">{{title}}</p><p class="mt-3 text-sm leading-7 text-slate-500">انتخابی از هنر دست و داستان سازندگان ایرانی.</p></div><div v-for="group in [['راهنمای خرید','روش‌های ارسال','پیگیری سفارش'],['خدمات مشتریان','سؤالات متداول','قوانین بازگشت'],['درباره ما','تماس با ما','همکاری با ما']]" :key="group[0]"><p class="font-black">{{group[0]}}</p><div class="mt-4 space-y-3 text-sm text-slate-500"><p>{{group[1]}}</p><p>{{group[2]}}</p></div></div></div></footer></div></template>
