<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller; use App\Models\Address; use Illuminate\Http\Request;
class AddressController extends Controller {
 public function index(Request $r){return Address::where('user_id',$r->user()->id)->latest('is_default')->get();}
 public function store(Request $r){$data=$this->data($r);$data['user_id']=$r->user()->id;if(!Address::where('user_id',$r->user()->id)->exists())$data['is_default']=true;if($data['is_default']??false)Address::where('user_id',$r->user()->id)->update(['is_default'=>false]);return response()->json(Address::create($data),201);}
 public function update(Request $r,Address $address){abort_unless($address->user_id===$r->user()->id,404);$data=$this->data($r);if($data['is_default']??false)Address::where('user_id',$r->user()->id)->whereKeyNot($address->id)->update(['is_default'=>false]);$address->update($data);return $address;}
 public function destroy(Request $r,Address $address){abort_unless($address->user_id===$r->user()->id,404);$wasDefault=$address->is_default;$address->delete();if($wasDefault)Address::where('user_id',$r->user()->id)->latest()->first()?->update(['is_default'=>true]);return response()->noContent();}
 private function data(Request $r):array{$data=$r->validate(['title'=>'sometimes|string|max:50','receiver_name'=>'required|string|max:100','receiver_mobile'=>['required','regex:/^09\d{9}$/'],'province_id'=>'required|integer|exists:provinces,id','city_id'=>'required|integer|exists:cities,id','address'=>'required|string|max:1000','postal_code'=>'required|digits:10','latitude'=>'nullable|numeric|between:-90,90','longitude'=>'nullable|numeric|between:-180,180','is_default'=>'sometimes|boolean']);$province=\Illuminate\Support\Facades\DB::table('provinces')->where('id',$data['province_id'])->where('is_active',true)->first();$city=\Illuminate\Support\Facades\DB::table('cities')->where('id',$data['city_id'])->where('province_id',$data['province_id'])->where('is_active',true)->first();if(!$province||!$city)throw \Illuminate\Validation\ValidationException::withMessages(['city_id'=>'شهر انتخاب‌شده متعلق به این استان نیست یا غیرفعال است.']);$data['province']=$province->name;$data['city']=$city->name;return $data;}
}
