<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller; use App\Models\Article; use App\Models\Comment; use App\Models\Order; use App\Models\Product; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB;
class EngagementController extends Controller {
 public function favorites(Request $r){return $r->user()->belongsToMany(Product::class,'favorites')->with(['variants','media'])->latest('favorites.created_at')->paginate(20);}
 public function toggleFavorite(Request $r,Product $product){$result=$r->user()->belongsToMany(Product::class,'favorites')->toggle($product->id);return ['is_favorite'=>count($result['attached'])>0];}
 public function savedArticles(Request $r){return $r->user()->belongsToMany(Article::class,'saved_articles')->where('status','published')->latest('saved_articles.created_at')->paginate(20);}
 public function toggleArticle(Request $r,Article $article){$result=$r->user()->belongsToMany(Article::class,'saved_articles')->toggle($article->id);return ['is_saved'=>count($result['attached'])>0];}
 public function comment(Request $r,string $type,int $id){$model=match($type){'product'=>Product::class,'article'=>Article::class,default=>abort(404)};$target=$model::findOrFail($id);$data=$r->validate(['body'=>'required|string|min:3|max:2000','rating'=>$type==='product'?'required|integer|between:1,5':'nullable|integer|between:1,5','parent_id'=>'nullable|exists:comments,id']);if($type==='product'&&empty($data['parent_id']))abort_if(Comment::where('user_id',$r->user()->id)->where('commentable_type',Product::class)->where('commentable_id',$id)->whereNull('parent_id')->exists(),422,'شما قبلاً برای این محصول نظر ثبت کرده‌اید.');$buyer=$type==='product'&&Order::where('user_id',$r->user()->id)->where('payment_status','paid')->whereHas('items',fn($q)=>$q->where('product_id',$id))->exists();$comment=$target->comments()->create($data+['user_id'=>$r->user()->id,'status'=>'pending','is_buyer'=>$buyer]);return response()->json(['message'=>'نظر شما پس از بررسی منتشر می‌شود.','comment'=>$comment],201);}
 public function vote(Request $r,Comment $comment){abort_unless($comment->status==='approved'&&$comment->commentable_type===Product::class,404);$exists=DB::table('comment_votes')->where(['comment_id'=>$comment->id,'user_id'=>$r->user()->id])->exists();if($exists)DB::table('comment_votes')->where(['comment_id'=>$comment->id,'user_id'=>$r->user()->id])->delete();else DB::table('comment_votes')->insert(['comment_id'=>$comment->id,'user_id'=>$r->user()->id,'created_at'=>now(),'updated_at'=>now()]);return ['helpful'=>!$exists,'votes_count'=>DB::table('comment_votes')->where('comment_id',$comment->id)->count()];}
}
