<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller;use App\Models\Product;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;
class ProductDiscoveryController extends Controller{
 public function suggestions(Request $r){$term=trim((string)$r->input('q'));if(mb_strlen($term)<2)return [];return Product::where('status','published')->where('title','like',"%{$term}%")->orderByDesc('view_count')->limit(8)->get(['title','slug']);}
 public function filters(){return ['brands'=>DB::table('brands')->where('is_active',true)->get(['id','title','slug']),'attributes'=>DB::table('attributes')->where('is_filterable',true)->get()->map(function($a){$a->values=DB::table('attribute_values')->where('attribute_id',$a->id)->orderBy('sort_order')->get();return $a;})];}
 public function related(Product $product){return Product::where('status','published')->whereKeyNot($product->id)->where(fn($q)=>$q->where('category_id',$product->category_id)->orWhere('brand_id',$product->brand_id))->with(['variants','media'])->limit(10)->get();}
 public function priceHistory(Product $product){return DB::table('price_histories')->join('product_variants','product_variants.id','=','price_histories.variant_id')->where('product_variants.product_id',$product->id)->select('price_histories.price','price_histories.recorded_at','product_variants.sku')->orderBy('recorded_at')->get();}
 public function questions(Product $product){return DB::table('product_questions')->join('users','users.id','=','product_questions.user_id')->where('product_id',$product->id)->where('status','approved')->select('product_questions.*','users.name as user_name')->latest('product_questions.created_at')->paginate(10);}
 public function ask(Request $r,Product $product){$data=$r->validate(['question'=>'required|string|min:5|max:1000']);$id=DB::table('product_questions')->insertGetId(['product_id'=>$product->id,'user_id'=>$r->user()->id,'question'=>$data['question'],'status'=>'pending','created_at'=>now(),'updated_at'=>now()]);return response()->json(['id'=>$id,'message'=>'پرسش شما پس از بررسی منتشر می‌شود.'],201);}
 public function alert(Request $r,Product $product){$data=$r->validate(['type'=>'required|in:price_drop,back_in_stock','variant_id'=>'nullable|exists:product_variants,id','target_price'=>'nullable|required_if:type,price_drop|integer|min:1']);$key=['user_id'=>$r->user()->id,'product_id'=>$product->id,'variant_id'=>$data['variant_id']??null,'type'=>$data['type']];$exists=DB::table('product_alerts')->where($key)->exists();if($exists){DB::table('product_alerts')->where($key)->delete();return ['enabled'=>false];}DB::table('product_alerts')->insert($key+['target_price'=>$data['target_price']??null,'created_at'=>now(),'updated_at'=>now()]);return ['enabled'=>true];}
}
